//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mirnes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresa
    {
        public Adresa()
        {
            this.Covjek = new HashSet<Covjek>();
            this.Dzemat = new HashSet<Dzemat>();
        }
    
        public int Id { get; set; }
        public string Grad { get; set; }
        public string Ulica { get; set; }
        public string Broj { get; set; }
        public string Drzava { get; set; }
        public string PostanskiBroj { get; set; }
    
        public virtual ICollection<Covjek> Covjek { get; set; }
        public virtual ICollection<Dzemat> Dzemat { get; set; }
    }
}
