//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mirnes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Covjek
    {
        public Covjek()
        {
            this.Dzemat1 = new HashSet<Dzemat>();
        }
    
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Email { get; set; }
        public int Adresa { get; set; }
        public Nullable<bool> IsImam { get; set; }
        public Nullable<bool> IsReis { get; set; }
        public Nullable<bool> IsUpravniOdbor { get; set; }
        public Nullable<int> Demat { get; set; }
    
        public virtual Adresa Adresa1 { get; set; }
        public virtual Dzemat Dzemat { get; set; }
        public virtual ICollection<Dzemat> Dzemat1 { get; set; }
    }
}
