//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mirnes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dzemat
    {
        public Dzemat()
        {
            this.Covjek = new HashSet<Covjek>();
        }
    
        public int Id { get; set; }
        public string Naziv { get; set; }
        public int Adresa { get; set; }
        public string Email { get; set; }
        public int Direktor { get; set; }
        public Nullable<int> BrojDzamija { get; set; }
    
        public virtual Adresa Adresa1 { get; set; }
        public virtual ICollection<Covjek> Covjek { get; set; }
        public virtual Covjek Covjek1 { get; set; }
    }
}
