//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mirnes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbmirnesEntities : DbContext
    {
        public dbmirnesEntities()
            : base("name=dbmirnesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Adresa> Adresa { get; set; }
        public DbSet<Covjek> Covjek { get; set; }
        public DbSet<Dzemat> Dzemat { get; set; }
        public DbSet<Korisnik> Korisnik { get; set; }
        public DbSet<Log> Log { get; set; }
    }
}
